/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package assignmenttwo;


/**
 * This is the generated Hello World Greeting App.
 */
public class App {

  private void sunPlanetMoon() {
  
  }

  private void heavenlyBody() {

  }

  private void solarSytem() {
    
  }

  /**
   * The App starting point.
   *
   * @param args Unused program arguments.
   */
  public static void main(String[] args) {
    App theApp = new App();
    theApp.sunPlanetMoon();
    theApp.heavenlyBody();
    theApp.solarSytem();
  }
}
